name: Deploy Application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Install dependencies
      run: yarn install

    - name: Run Postman Collection
      run: yarn test:postman

    # Ajoutez ici les étapes spécifiques à votre déploiement
    # Par exemple pour Vercel, Netlify, AWS, etc.
